server:
  port: 8000

spring:
  application:
      name: JavaService
  datasource:

    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_face_attd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置mapper
mybatis:
  #mapper接口
  mapper-locations: classpath:mapper/*.xml
  #实体类
  type-aliases-package: com.wcf.javaservicer.pojo
  #mybatis内置的配置
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

python_url: http://127.0.0.1:8888

upload: F:/upload/ #自定义文件上传路径

uploadface: F:/upload/facepicture/
